name: Cost Impact Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.yaml'
      - '**.yml'
      - 'manifests/**'
      - 'k8s/**'

jobs:
  cost-estimate:
    name: Estimate Deployment Cost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install kube-cost plugin
        run: |
          # Download and install kubectl-cost plugin
          curl -L https://github.com/deepcost/kube-cost-exporter/releases/latest/download/kubectl-cost-linux-amd64 -o kubectl-cost
          chmod +x kubectl-cost
          sudo mv kubectl-cost /usr/local/bin/

      - name: Set up port forwarding to Prometheus
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig

          # Port forward Prometheus
          kubectl port-forward -n monitoring svc/prometheus-operated 9090:9090 &
          sleep 5

      - name: Analyze changed manifests
        id: cost-analysis
        run: |
          # Find all changed YAML files
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '\.ya?ml$' | grep -v '.github' || true)

          if [ -z "$CHANGED_FILES" ]; then
            echo "No YAML manifests changed"
            exit 0
          fi

          # Extract resource requests from manifests
          TOTAL_CPU=0
          TOTAL_MEM=0

          for file in $CHANGED_FILES; do
            if grep -q "kind: Deployment\|kind: StatefulSet\|kind: DaemonSet" "$file"; then
              # Extract CPU requests (in millicores)
              CPU=$(grep -A 5 "resources:" "$file" | grep "cpu:" | head -1 | awk '{print $2}' | sed 's/m//' || echo "0")
              # Extract memory requests (in Mi)
              MEM=$(grep -A 5 "resources:" "$file" | grep "memory:" | head -1 | awk '{print $2}' | sed 's/Mi//' || echo "0")

              # Extract replica count
              REPLICAS=$(grep "replicas:" "$file" | head -1 | awk '{print $2}' || echo "1")

              TOTAL_CPU=$((TOTAL_CPU + CPU * REPLICAS))
              TOTAL_MEM=$((TOTAL_MEM + MEM * REPLICAS))
            fi
          done

          echo "total_cpu=$TOTAL_CPU" >> $GITHUB_OUTPUT
          echo "total_mem=$TOTAL_MEM" >> $GITHUB_OUTPUT

      - name: Estimate cost
        id: estimate
        run: |
          # Average cost per vCPU per month: ~$30
          # Average cost per GB RAM per month: ~$4
          CPU_CORES=$(echo "scale=2; ${{ steps.cost-analysis.outputs.total_cpu }} / 1000" | bc)
          MEM_GB=$(echo "scale=2; ${{ steps.cost-analysis.outputs.total_mem }} / 1024" | bc)

          CPU_COST=$(echo "scale=2; $CPU_CORES * 30" | bc)
          MEM_COST=$(echo "scale=2; $MEM_GB * 4" | bc)
          TOTAL_COST=$(echo "scale=2; $CPU_COST + $MEM_COST" | bc)

          echo "cpu_cores=$CPU_CORES" >> $GITHUB_OUTPUT
          echo "mem_gb=$MEM_GB" >> $GITHUB_OUTPUT
          echo "estimated_monthly_cost=$TOTAL_COST" >> $GITHUB_OUTPUT

      - name: Get current namespace cost
        id: current-cost
        env:
          KUBECONFIG: /tmp/kubeconfig
        run: |
          # Get current cost for affected namespaces
          NAMESPACE=$(grep "namespace:" $CHANGED_FILES | head -1 | awk '{print $2}' || echo "default")

          CURRENT_COST=$(kubectl cost namespace $NAMESPACE --prometheus-url http://localhost:9090 --window 30d | tail -1 | awk '{print $4}' | tr -d '$' || echo "0")

          echo "current_cost=$CURRENT_COST" >> $GITHUB_OUTPUT
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT

      - name: Calculate cost increase
        id: cost-increase
        run: |
          CURRENT=${{ steps.current-cost.outputs.current_cost }}
          ESTIMATED=${{ steps.estimate.outputs.estimated_monthly_cost }}

          if [ "$CURRENT" = "0" ]; then
            INCREASE_PCT=0
          else
            INCREASE_PCT=$(echo "scale=2; ($ESTIMATED / $CURRENT) * 100" | bc)
          fi

          echo "increase_pct=$INCREASE_PCT" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const cpuCores = '${{ steps.estimate.outputs.cpu_cores }}';
            const memGb = '${{ steps.estimate.outputs.mem_gb }}';
            const estimatedCost = '${{ steps.estimate.outputs.estimated_monthly_cost }}';
            const currentCost = '${{ steps.current-cost.outputs.current_cost }}';
            const namespace = '${{ steps.current-cost.outputs.namespace }}';
            const increasePct = '${{ steps.cost-increase.outputs.increase_pct }}';

            const body = `## 💰 Cost Impact Analysis

            **Estimated Resource Requirements:**
            - CPU: ${cpuCores} cores
            - Memory: ${memGb} GB

            **Cost Estimate:**
            - Estimated monthly cost: **$${estimatedCost}**
            - Current namespace cost: $${currentCost}
            - Increase: ${increasePct}%

            **Namespace:** \`${namespace}\`

            ---

            ${parseFloat(increasePct) > 20 ? '⚠️ **Warning:** This change increases costs by more than 20%!' : '✅ Cost increase is within acceptable range.'}

            <details>
            <summary>💡 Cost Optimization Tips</summary>

            - Review resource requests - are they right-sized?
            - Consider using Horizontal Pod Autoscaler to scale based on demand
            - Use spot/preemptible instances for non-critical workloads
            - Check if resource limits are necessary
            </details>
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Fail if cost increase is too high
        if: steps.cost-increase.outputs.increase_pct > 50
        run: |
          echo "::error::Cost increase of ${{ steps.cost-increase.outputs.increase_pct }}% exceeds 50% threshold!"
          exit 1

      - name: Cleanup
        if: always()
        run: |
          pkill -f "port-forward" || true
          rm -f /tmp/kubeconfig
